Added Dockerfile and ci-cd.yml configurations

diff --git a/.github/ci-cd.yml b/.github/ci-cd.yml
--- a/.github/ci-cd.yml
+++ b/.github/ci-cd.yml
@@ -1,10 +1,45 @@
-name: CI CD pipeline
+name: demo pipeline
+
 on:
   push:
-    branches:
-      - main
-      - develop 
-  pull_request:
-    branches:
-      - main
-      - develop
+    branches: [ "master" ]
+
+jobs:
+  build:
+    runs-on: [ubuntu-latest]
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
+        with:
+          distribution: 'temurin'
+          java-version: '17'
+      - name: Build with Maven
+        run: mvn clean install -DskipTests
+      - name: Login to docker hub
+        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
+      - name: Build docker image
+        run: docker build -t springbootaws1.
+      - name: Push docker image
+        run: docker push springbootaws1:latest
+
+  deploy:
+    needs: build
+    runs-on: [<ec2 instance runner's lable>]
+    steps:
+      - name: Check Docker Installation
+        run: |
+          if ! [ -x "$(command -v docker)" ]; then
+            echo "Error: Docker is not installed." >&2
+            exit 1
+          fi
+      - name: Pull image from docker hub
+        run: sudo docker pull springbootaws1:latest
+      - name: Delete existing container
+        run: |
+          if [ "$(sudo docker ps -aq -f name=demo)" ]; then
+            sudo docker rm -f demo
+          fi
+      - name: Run docker container
+        run: sudo docker run -d -p 8080:8080 --name demo springbootaws1
